# Generated by Django 5.1.4 on 2024-12-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_produto_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='setor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
